# Generated by Django 3.0.5 on 2021-02-23 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('desc', models.TextField(default='No Description', max_length=100)),
                ('Phone', models.PositiveIntegerField()),
                ('Age', models.PositiveIntegerField()),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
